# Numpy Part - 1

NumPy is a Python package. It stands for 'Numerical Python'. It is a library consisting of multidimensional array objects and a collection of routines for processing of array.

In [2]:
import numpy as np

In [3]:
l=[1,2,3,4]

In [4]:
ar = np.array(l)

In [5]:
ar

array([1, 2, 3, 4])

In [6]:
type(ar)

numpy.ndarray

In [7]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
np.asarray(l)  # asarray() This function is used to create an array by using the existing data in the form of lists, or tuples.

array([1, 2, 3, 4])

In [10]:
np.asanyarray(l)

array([1, 2, 3, 4])

In [11]:
a=[1,2,3,4,5]

In [12]:
np.asanyarray(a)  # it is use to change in array

array([1, 2, 3, 4, 5])

In [13]:
b = np.matrix(l)  # matrix always in 2D form .Matrix is subset of array

In [14]:
b

matrix([[1, 2, 3, 4]])

In [16]:
np.asanyarray(b)  # It does not change into array because matrix is subset of array

matrix([[1, 2, 3, 4]])

In [17]:
a

[1, 2, 3, 4, 5]

In [18]:
c = a

In [19]:
a

[1, 2, 3, 4, 5]

In [20]:
c

[1, 2, 3, 4, 5]

In [22]:
c[0] = 100

In [23]:
c

[100, 2, 3, 4, 5]

In [24]:
a

[100, 2, 3, 4, 5]

In [25]:
d=np.copy(a)

In [26]:
d

array([100,   2,   3,   4,   5])

In [27]:
a

[100, 2, 3, 4, 5]

In [28]:
a[1]=400

In [29]:
a

[100, 400, 3, 4, 5]

In [30]:
d

array([100,   2,   3,   4,   5])

In [31]:
np.fromfunction(lambda i , j :i==j,(3,3))  #fromfunction() function construct an array by executing a function over each coordinate and the resulting array, 

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [32]:
np.fromfunction(lambda i , j :i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [33]:
iterable = (i*i for i in range(5))

In [34]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [37]:
np.fromstring('234 334' , sep=" ")

array([234., 334.])

In [40]:
np.fromstring('2,4' , sep=',')

array([2., 4.])

In [41]:
# Numpy - DataType

In [42]:
l=[2,3,4,5,44,22]

In [43]:
ar = np.array(l)

In [44]:
ar

array([ 2,  3,  4,  5, 44, 22])

In [45]:
ar.ndim

1

In [46]:
ar2 = np.array([[1,2,3],[22,33,44]])

In [47]:
ar2

array([[ 1,  2,  3],
       [22, 33, 44]])

In [48]:
ar2.ndim   #It give dimension of array

2

In [49]:
ar2.size  #It calculate the number of elelment in array

6

In [50]:
ar2.shape  #Show row and col

(2, 3)

In [52]:
ar2.dtype

dtype('int64')

In [62]:
ar22 = np.array([(1.7,2.,3),(22,33,11)])

In [65]:
ar22

array([[ 1.7,  2. ,  3. ],
       [22. , 33. , 11. ]])

In [66]:
ar22.dtype

dtype('float64')

In [67]:
list(range(5))     #range always is in Integer

[0, 1, 2, 3, 4]

In [68]:
np.arange(2.3,5.6) #arange value is in float

array([2.3, 3.3, 4.3, 5.3])

In [69]:
np.arange(2.3,5.6,0.3)  #0.3 is jump value

array([2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3])

In [70]:
list(np.arange(2.3,5.6,0.3) )

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [71]:
np.linspace(1,5,10)  #The numpy.linspace() function returns number spaces evenly w.r.t interval.

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [72]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [74]:
np.zeros((3,4)) #2D

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [75]:
np.zeros((3,4,2))  #3D

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [2]:
import numpy as np

In [3]:
np.ones(4)

array([1., 1., 1., 1.])

In [4]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [5]:
on = np.ones((2,3,2))

In [6]:
on


array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [7]:
on + 5

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [8]:
np.empty((3,6))

array([[4.65852803e-310, 0.00000000e+000, 6.93005950e-310,
        6.93005859e-310, 6.93005858e-310, 6.93005859e-310],
       [6.93005859e-310, 6.93005970e-310, 6.93005950e-310,
        6.93005951e-310, 6.93005951e-310, 6.93005951e-310],
       [6.93005950e-310, 6.93005951e-310, 6.93005950e-310,
        6.93005950e-310, 6.93005950e-310, 6.93005879e-310]])

In [9]:
np.eye(4)  # eye is use for create identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
np.linspace(2,4,20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [11]:
np.logspace(2,4,10, base=2)

array([ 4.        ,  4.66611616,  5.44316   ,  6.34960421,  7.4069977 ,
        8.64047791, 10.0793684 , 11.75787594, 13.71590373, 16.        ])

In [12]:
arr = np.random.randn(3,4)  #The random. randn() is a numpy library function that returns an array of random samples from the standard normal distribution.

In [13]:
arr

array([[ 0.83845296,  0.24662526, -0.49215337, -2.03731378],
       [ 1.1068411 ,  1.82793748,  1.16224824,  1.17900945],
       [-0.78271674,  1.92820774,  0.68197873,  1.63388617]])

In [14]:
import pandas as pd

In [15]:
pd.DataFrame(arr)

0         1         2         3
0  0.838453  0.246625 -0.492153 -2.037314
1  1.106841  1.827937  1.162248  1.179009
2 -0.782717  1.928208  0.681979  1.633886

In [16]:
np.random.rand(3,4)  # numpy. random. rand from a uniform distribution (in the range [0,1)).

array([[0.32795447, 0.15188295, 0.66455785, 0.69650094],
       [0.06871662, 0.04174072, 0.37147923, 0.49716452],
       [0.66458536, 0.88382351, 0.82955781, 0.79168658]])

In [18]:
np.random.randint(1,110,(3,4))  #It retuen only integer value 

array([[94, 49, 68, 87],
       [48, 33, 89, 13],
       [46, 72, 72, 67]])

In [19]:
pd.DataFrame(np.random.randint(1,100,(3,4)))

0   1   2   3
0  69  84  21  48
1  25  95  25  10
2  71  69  13  26

In [20]:
pd.DataFrame(np.random.randint(1,100,(3,4))).to_csv('test.csv')

In [21]:
#change into other shape
arr = np.random.rand(3,4)

In [22]:
arr

array([[0.6302234 , 0.88943564, 0.96193606, 0.09551514],
       [0.37884024, 0.17219042, 0.0438734 , 0.8733645 ],
       [0.06767807, 0.35815703, 0.77527816, 0.42256216]])

In [23]:
arr.reshape(6,2)

array([[0.6302234 , 0.88943564],
       [0.96193606, 0.09551514],
       [0.37884024, 0.17219042],
       [0.0438734 , 0.8733645 ],
       [0.06767807, 0.35815703],
       [0.77527816, 0.42256216]])

In [24]:
arr.reshape(6,-1)   #Negative value auto complte the second value

array([[0.6302234 , 0.88943564],
       [0.96193606, 0.09551514],
       [0.37884024, 0.17219042],
       [0.0438734 , 0.8733645 ],
       [0.06767807, 0.35815703],
       [0.77527816, 0.42256216]])

In [25]:
arr1 = arr.reshape(6,-134456)

In [26]:
arr1

array([[0.6302234 , 0.88943564],
       [0.96193606, 0.09551514],
       [0.37884024, 0.17219042],
       [0.0438734 , 0.8733645 ],
       [0.06767807, 0.35815703],
       [0.77527816, 0.42256216]])

In [27]:
arr1[1][1]

0.09551513585757199

In [28]:
arr1[2:5,1]

array([0.17219042, 0.8733645 , 0.35815703])

In [31]:
arr = np.random.randint(1,100,(5,5))   #Number range is 1 to 100 and it is in 5x5 matrix


In [30]:
arr

array([[50, 80, 68, 61, 59],
       [70,  6, 47, 47, 82],
       [96, 91, 73, 23, 63],
       [34, 21, 91, 98, 41],
       [76, 17, 81, 84,  8]])

In [33]:
arr[arr>50]

array([87, 99, 86, 57, 68, 90, 67, 79, 65, 87, 65])

In [34]:
arr

array([[87, 99, 86, 57,  4],
       [ 6, 29, 68, 90, 67],
       [79,  6, 50, 19, 65],
       [48, 87, 48, 50, 18],
       [ 7,  3, 65,  9, 46]])

In [35]:
arr[2:4 ,[1,2]]    #slicing and indexing

array([[ 6, 50],
       [87, 48]])

In [36]:
arr[0][0]

87

In [37]:
arr[0][0]=5000

In [38]:
arr

array([[5000,   99,   86,   57,    4],
       [   6,   29,   68,   90,   67],
       [  79,    6,   50,   19,   65],
       [  48,   87,   48,   50,   18],
       [   7,    3,   65,    9,   46]])

In [39]:
arr1=np.random.randint(1,3,(3,3))

arr2 = np.random.randint(1,3,(3,3))

In [40]:
arr1

array([[1, 1, 2],
       [1, 2, 1],
       [2, 2, 2]])

In [41]:
arr2

array([[2, 2, 1],
       [2, 1, 1],
       [1, 2, 1]])

In [42]:
arr1+arr2   # Add index by index element

array([[3, 3, 3],
       [3, 3, 2],
       [3, 4, 3]])

In [43]:
arr1-arr2

array([[-1, -1,  1],
       [-1,  1,  0],
       [ 1,  0,  1]])

In [44]:
arr1/arr2

array([[0.5, 0.5, 2. ],
       [0.5, 2. , 1. ],
       [2. , 1. , 2. ]])

In [45]:
arr1*arr2  # it gives index by multiplication

array([[2, 2, 2],
       [2, 2, 1],
       [2, 4, 2]])

In [46]:
arr1@arr2    #  @  It gives a matrix multiplication

array([[ 6,  7,  4],
       [ 7,  6,  4],
       [10, 10,  6]])

In [47]:
arr1/0   #it gives infinite not an error

/tmp/ipykernel_1127/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [48]:
 arr1 +100

array([[101, 101, 102],
       [101, 102, 101],
       [102, 102, 102]])

In [49]:
arr1**2

array([[1, 1, 4],
       [1, 4, 1],
       [4, 4, 4]])

In [ ]:
#Numpy - Broadcasting

In [50]:
arr = np.zeros((4,4))

In [51]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [52]:
row = np.array([1,2,3,4])

In [53]:
row

array([1, 2, 3, 4])

In [54]:
arr+row         #In which add element in each row by row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [55]:
#For add each element in col by col

In [59]:
row.T                #Transpose  . It is 1 D  so it is not transposes

array([1, 2, 3, 4])

In [61]:
col = np.array([[1,2,3,4]])

In [62]:
col

array([[1, 2, 3, 4]])

In [65]:
col.T

array([[1],
       [2],
       [3],
       [4]])

In [66]:
col.T+arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [64]:
col

array([[1, 2, 3, 4]])

In [67]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [69]:
arr1=np.random.randint(1,4,(3,4))

In [70]:
arr1

array([[2, 1, 2, 3],
       [2, 2, 3, 3],
       [2, 1, 1, 2]])

In [71]:
np.sqrt(arr1)

array([[1.41421356, 1.        , 1.41421356, 1.73205081],
       [1.41421356, 1.41421356, 1.73205081, 1.73205081],
       [1.41421356, 1.        , 1.        , 1.41421356]])

In [72]:
np.exp(arr1)

array([[ 7.3890561 ,  2.71828183,  7.3890561 , 20.08553692],
       [ 7.3890561 ,  7.3890561 , 20.08553692, 20.08553692],
       [ 7.3890561 ,  2.71828183,  2.71828183,  7.3890561 ]])

In [73]:
np.log10(arr1)

array([[0.30103   , 0.        , 0.30103   , 0.47712125],
       [0.30103   , 0.30103   , 0.47712125, 0.47712125],
       [0.30103   , 0.        , 0.        , 0.30103   ]])

# Part -2

In [74]:
#Numpy - Array Manipulation

In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,10,(3,4))

In [3]:
arr

array([[6, 6, 9, 3],
       [2, 4, 1, 4],
       [1, 6, 8, 5]])

In [4]:
arr.reshape(6,2)

array([[6, 6],
       [9, 3],
       [2, 4],
       [1, 4],
       [1, 6],
       [8, 5]])

In [5]:
arr.reshape(2,6)

array([[6, 6, 9, 3, 2, 4],
       [1, 4, 1, 6, 8, 5]])

In [6]:
arr.T

array([[6, 2, 1],
       [6, 4, 6],
       [9, 1, 8],
       [3, 4, 5]])

In [7]:
arr

array([[6, 6, 9, 3],
       [2, 4, 1, 4],
       [1, 6, 8, 5]])

In [8]:
arr.flatten()  #It change any array in 1 Dimension 

array([6, 6, 9, 3, 2, 4, 1, 4, 1, 6, 8, 5])

In [9]:
arr1 = np.array([1,2,3,4])

In [10]:
arr1.ndim

1

In [11]:
np.expand_dims(arr1,axis=1)        #It expand dim from 1D to 2D array

array([[1],
       [2],
       [3],
       [4]])

In [12]:
np.expand_dims(arr1,axis=0) 

array([[1, 2, 3, 4]])

In [87]:
arr


array([[1, 2, 4, 9],
       [8, 5, 3, 8],
       [9, 3, 4, 9]])

In [88]:
data = np.array([[1], [2], [3]])

In [89]:
data

array([[1],
       [2],
       [3]])

In [90]:
np.squeeze(data)   #squeeze() function is used when we want to remove single-dimensional entries from the shape of an array

array([1, 2, 3])

In [ ]:
arr1

In [13]:
np.repeat(arr1,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [14]:
np.roll(arr1 , 3)   #The roll() function is used to roll array elements along a given axis

array([2, 3, 4, 1])

In [15]:
arr1

array([1, 2, 3, 4])

In [16]:
np.diag(arr1)  #The diag() function is used to extract a diagonal or construct a diagonal array.

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [17]:
#Numpy - Binary Operation

In [18]:
arr1  = np.random.randint(1,10,(3,4))

In [19]:
arr2 = np.random.randint(1,10,(3,4))

In [20]:
arr1

array([[1, 1, 8, 7],
       [6, 5, 3, 8],
       [9, 7, 2, 4]])

In [21]:
arr2

array([[6, 2, 6, 5],
       [9, 2, 3, 6],
       [8, 8, 9, 2]])

In [22]:
arr1+arr2        #Add element index by index

array([[ 7,  3, 14, 12],
       [15,  7,  6, 14],
       [17, 15, 11,  6]])

In [23]:
arr1*arr2

array([[ 6,  2, 48, 35],
       [54, 10,  9, 48],
       [72, 56, 18,  8]])

In [24]:
arr1 ** arr2

array([[       1,        1,   262144,    16807],
       [10077696,       25,       27,   262144],
       [43046721,  5764801,      512,       16]])

In [25]:
arr1 & arr2

array([[0, 0, 0, 5],
       [0, 0, 3, 0],
       [8, 0, 0, 0]])

In [26]:
arr1

array([[1, 1, 8, 7],
       [6, 5, 3, 8],
       [9, 7, 2, 4]])

In [27]:
arr2

array([[6, 2, 6, 5],
       [9, 2, 3, 6],
       [8, 8, 9, 2]])

In [29]:
~arr1

array([[ -2,  -2,  -9,  -8],
       [ -7,  -6,  -4,  -9],
       [-10,  -8,  -3,  -5]])

In [30]:
arr1 | arr2

array([[ 7,  3, 14,  7],
       [15,  7,  3, 14],
       [ 9, 15, 11,  6]])

In [31]:
arr1>arr2

array([[False, False,  True,  True],
       [False,  True, False,  True],
       [ True, False, False,  True]])

In [32]:
#Numpy - String Function

In [33]:
arr = np.array(["mk","kumar"])

In [34]:
arr

array(['mk', 'kumar'], dtype='<U5')

In [35]:
np.char.upper(arr)

array(['MK', 'KUMAR'], dtype='<U5')

In [36]:
np.char.title(arr)

array(['Mk', 'Kumar'], dtype='<U5')

In [37]:
np.char.capitalize(arr)

array(['Mk', 'Kumar'], dtype='<U5')

In [38]:
# Numpy - Mathematical Function

In [39]:
import numpy as np

In [40]:
arr1


array([[1, 1, 8, 7],
       [6, 5, 3, 8],
       [9, 7, 2, 4]])

In [41]:
np.sin(arr1)

array([[ 0.84147098,  0.84147098,  0.98935825,  0.6569866 ],
       [-0.2794155 , -0.95892427,  0.14112001,  0.98935825],
       [ 0.41211849,  0.6569866 ,  0.90929743, -0.7568025 ]])

In [42]:
np.cos(arr1)

array([[ 0.54030231,  0.54030231, -0.14550003,  0.75390225],
       [ 0.96017029,  0.28366219, -0.9899925 , -0.14550003],
       [-0.91113026,  0.75390225, -0.41614684, -0.65364362]])

In [44]:
np.tan(arr1)

array([[ 1.55740772,  1.55740772, -6.79971146,  0.87144798],
       [-0.29100619, -3.38051501, -0.14254654, -6.79971146],
       [-0.45231566,  0.87144798, -2.18503986,  1.15782128]])

In [45]:
np.tanh(arr1)  # It is used to calculate the hyperbolic tangent for all the elements of the array passed as the argument.

array([[0.76159416, 0.76159416, 0.99999977, 0.99999834],
       [0.99998771, 0.9999092 , 0.99505475, 0.99999977],
       [0.99999997, 0.99999834, 0.96402758, 0.9993293 ]])

In [46]:
np.log10(arr1)

array([[0.        , 0.        , 0.90308999, 0.84509804],
       [0.77815125, 0.69897   , 0.47712125, 0.90308999],
       [0.95424251, 0.84509804, 0.30103   , 0.60205999]])

In [47]:
np.exp(arr1)

array([[2.71828183e+00, 2.71828183e+00, 2.98095799e+03, 1.09663316e+03],
       [4.03428793e+02, 1.48413159e+02, 2.00855369e+01, 2.98095799e+03],
       [8.10308393e+03, 1.09663316e+03, 7.38905610e+00, 5.45981500e+01]])

In [48]:
np.sqrt(arr1)

array([[1.        , 1.        , 2.82842712, 2.64575131],
       [2.44948974, 2.23606798, 1.73205081, 2.82842712],
       [3.        , 2.64575131, 1.41421356, 2.        ]])

In [49]:
np.power(arr1,2)

array([[ 1,  1, 64, 49],
       [36, 25,  9, 64],
       [81, 49,  4, 16]])

In [50]:
np.mean(arr1)

5.083333333333333

In [51]:
np.median(arr1)

5.5

In [52]:
np.std(arr1)

2.722080495176846

In [53]:
np.max(arr1)

9

# Part - 3

In [54]:
# Sort , Search and Counting Function

In [55]:
import numpy as np

In [56]:
arr = np.array([1,2,3,4,5,6,778,9])

In [57]:
arr

array([  1,   2,   3,   4,   5,   6, 778,   9])

In [58]:
np.sort(arr)

array([  1,   2,   3,   4,   5,   6,   9, 778])

In [59]:
np.searchsorted(arr,34)

6

In [60]:
arr1=np.array([0,1,2,3,4,0,0,0,0,0])

In [61]:
arr1

array([0, 1, 2, 3, 4, 0, 0, 0, 0, 0])

In [62]:
np.count_nonzero(arr1)

4

In [63]:
arr

array([  1,   2,   3,   4,   5,   6, 778,   9])

In [64]:
np.where(arr>6)

(array([6, 7]),)

In [65]:
np.extract(arr>6,arr)

array([778,   9])

In [66]:
#Numpy - Byte Swapping

In [67]:
arr

array([  1,   2,   3,   4,   5,   6, 778,   9])

In [68]:
arr.byteswap()

array([ 72057594037927936, 144115188075855872, 216172782113783808,
       288230376151711744, 360287970189639680, 432345564227567616,
       721420365309411328, 648518346341351424])

In [69]:
#Numpy - Copies and views

In [70]:
arr

array([  1,   2,   3,   4,   5,   6, 778,   9])

In [71]:
a=np.copy(arr) #The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy

In [72]:
a

array([  1,   2,   3,   4,   5,   6, 778,   9])

In [73]:
b=arr.view()   #The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [74]:
b

array([  1,   2,   3,   4,   5,   6, 778,   9])

In [75]:
arr

array([  1,   2,   3,   4,   5,   6, 778,   9])

In [76]:
b[0]=67

In [77]:
b

array([ 67,   2,   3,   4,   5,   6, 778,   9])

In [78]:
arr

array([ 67,   2,   3,   4,   5,   6, 778,   9])

In [79]:
b

array([ 67,   2,   3,   4,   5,   6, 778,   9])

In [80]:
# Numpy - Matrix Library

In [82]:
import numpy.matlib as nm

In [83]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [84]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [85]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [86]:
#Numpy - Linear Algebra

In [87]:
arr1 = np.random.randint([[2,3], [4,5]])

In [88]:
arr2 = np.random.randint([[2,3], [4,5]])

In [89]:
arr1

array([[1, 1],
       [0, 4]])

In [90]:
arr2

array([[0, 2],
       [2, 3]])

In [91]:
np.dot(arr1,arr2)

array([[ 2,  5],
       [ 8, 12]])

In [92]:
arr1@arr2

array([[ 2,  5],
       [ 8, 12]])